### ISSUE TITLE
Getting "ERROR Google" when sending new print job after some inactivity time 

### ISSUE THREAD

**Issue by hubertbanas** [davesteele/cloudprint-service#12]
I would like to know if anyone encounter similar issue and if there is any recommended workaround

What happens is when the cloudprint service is started everything seems to be OK. Everything I send gets printed immediately. However, I would get "ERROR Google" if there is no print jobs sent for an hour or two. The only way to recover is to 

sudo service cloudprintd restart

which again will restore printing capabilities for some time but would "ERROR Google" later. 

My workaround for now is to have crontab restart cloudprintd every 15 minutes. It is ugly but works. It is possible that 30 minutes or 45 minutes would do it. I would need more debug to determine exact timing. 

I believe I tried FAST_POLL='-f' on my other server but got same results so I left crontab workaround I mentioned earlier.

My system is headless debian wheezy 7.4

uname -a
Linux servername 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux

cat /etc/debian_version 
7.4

dpkg -l | grep cloudprint
ii  cloudprint                         0.11-3.1                      all          Google Cloud Print proxy
ii  cloudprint-service                 0.11-3.1                      all          provide a service for sharing printers on Google Cloud Print

And here is some logs:

Installed cloudprint cloudprint-service and started the process:

Feb 27 10:10:37 servername cloudprint.py: Updated Printer MFC7360N
Feb 27 10:10:37 servername cloudprint.py: Establishing connection to xmpp server talk.google.com:5223
Feb 27 10:10:37 servername cloudprint.py: xmpp connection established
Feb 27 10:13:33 servername cloudprint.py: Polling for jobs on MFC7360N

Sending 1st print job from nexus 5 

Feb 27 10:13:34 servername cloudprint.py: SUCCESS Google

1st print job gets printed successfully
Also https://www.google.com/cloudprint/#jobs shows that the 1st job was successful

Waiting few hours without sending any new print jobs:

Feb 27 10:35:05 servername cloudprint.py: ERROR: Could not Connect to Cloud Service. Will Try again in 60 Seconds
Feb 27 10:36:06 servername cloudprint.py: Polling for jobs on MFC7360N
Feb 27 10:36:06 servername cloudprint.py: Establishing connection to xmpp server talk.google.com:5223
Feb 27 10:36:06 servername cloudprint.py: xmpp connection established
Feb 27 11:36:06 servername cloudprint.py: Polling for jobs on MFC7360N
Feb 27 12:30:33 servername cloudprint.py: Polling for jobs on MFC7360N

Sending 2nd print job from nexus 5 -  seeing the following error in the log:

Feb 27 12:30:34 servername cloudprint.py: ERROR Google

No job gets printed. However, https://www.google.com/cloudprint/#jobs shows that the 2nd job was printed successfully

Let me know if there is any more debug needed.
Thanks
Hubert

**Comment by davesteele** [comment]
I'm closing this as possibly obsolete. Authentication, job completion, and retry logic have changed since the last report.
