### ISSUE TITLE
After first other jobs fail

### ISSUE THREAD

**Issue by charliemaiors** [davesteele/cloudprint-service#14]
Mar  7 11:34:55 raspberrypi cloudprint.py: xmpp connection established
Mar  7 11:38:51 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 11:38:53 raspberrypi cloudprint.py: SUCCESS Document1.pdf
Mar  7 12:38:53 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 13:38:54 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 14:38:54 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 15:38:54 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 16:38:55 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 17:38:55 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 18:38:56 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 19:38:56 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 19:57:59 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 19:58:02 raspberrypi cloudprint.py: ERROR Document2.pdf
Mar  7 19:58:18 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 19:58:25 raspberrypi cloudprint.py: ERROR Document3.pdf
Mar  7 20:58:25 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 21:58:25 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 22:58:26 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  7 23:58:26 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 00:58:26 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 01:58:27 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 02:58:27 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 03:58:28 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 04:58:28 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 05:58:29 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 06:58:30 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 07:58:30 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 08:58:30 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 09:58:31 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 10:58:31 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 11:58:32 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 12:58:32 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 13:58:33 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 14:58:33 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 15:58:34 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 16:07:25 raspberrypi cloudprint.py: Polling for jobs on HpLaserjet
Mar  8 16:07:32 raspberrypi cloudprint.py: ERROR Document4.pdf

this is my user.log, after i've succesfully printed Document1 the others fail, after a service restart is the same...I can print one document at time...

**Comment by davesteele** [comment]
There have been many releases and many changes since this issue was last referenced. Closing.
