### ISSUE TITLE
Add PPA to launchpad.net?

### ISSUE THREAD

**Issue by rubic** [davesteele/cloudprint-service#15]
Would it be possible to add this PPA to [launchpad.net](http://www.jamescoyle.net/how-to/529-add-launchpad-ppa-repository-to-ubuntu)?

We are provisioning print servers via [saltstack](http://saltstack.org) and having the PPA directly accessible from [launchpad.net](https://launchpad.net/ubuntu/+ppas) would be convenient.

**Comment by davesteele** [comment]
I'd have no problem with that. Are you aware that it is in Universe?

**Comment by bits01** [comment]
It's not available for trusty (14.04 LTS) in Universe, just utopic and vivid.
