### ISSUE TITLE
Problem when cloudprint PPA enabled

### ISSUE THREAD

**Issue by mfraser** [davesteele/cloudprint-service#16]
Recently when the PPA is enabled, every time I do an update it fails with the following error:
Problem with MergeList /var/lib/apt/lists/davesteele.github.io_cloudprint-service_repo_dists_cloudprintppa_main_i18n_Translation-en
The package lists or status file could not be parsed or opened.
Can't call method "policy" on an undefined value at /usr/bin/apt-show-versions line 56.
E: Problem executing scripts APT::Update::Post-Invoke-Success 'test -x /usr/bin/apt-show-versions || exit 0 ; apt-show-versions -i'
E: Sub-process returned an error code

**Comment by bits01** [comment]
Having the same issue on Linux Mint 17.1

**Comment by davesteele** [comment]
Does this address the issue (the repo is created with reprepo)?

http://unix.stackexchange.com/questions/163128/reprepro-repository-is-missing-some-files

**Comment by bits01** [comment]
Any ideas how it just broke recently? It has been working fine for months.

**Comment by davesteele** [comment]
Nothing has changed on this end.

**Comment by davesteele** [comment]
I have a Mint 17 32 bit environment available. No problems with apt or Update Manager. More information?

**Comment by bits01** [comment]
Mine is Mint 17.1 Rebecca MATE x64. It seems to get into this state once in a while. The common suggestions when something like this happens are to delete all the files in /var/lib/apt/lists/* and apt-get update again, but that does not work for me. The only thing that helps is to go in the the Update Manager (mintupdate app) > Edit > Software sources > Maintenance > Fix MergeList problems. Then I can do an apt-get update again, for a while at least until it happens again.
I will look at it some more next time it happens.

**Comment by davesteele** [comment]
PPA is no more. See #36.
