### ISSUE TITLE
service requiring re-authentication?

### ISSUE THREAD

**Issue by jhorrell** [davesteele/cloudprint-service#19]
I am running on raspberry pi with raspbian.

Followed the instructions and everything worked, but after a couple of months, stopped working. Documents would look like they had been printed when looking at the print jobs on the cloudprint web console for the printer (www.google.com/cloudprint), but would not appear at the printer. The service on the pi seemed to be still running (ps aux command gave "/usr/bin/python /usr/sbin/cloudprintd -d -u -a /var/lib/cloudprintd/authfile -p /var/run/cloudprint.pid").

On halting ("sudo /sbin/halt") and restarting, the service was no longer running afterwards.

Re-authenticating “sudo service cloudprintd login” followed by "sudo reboot" seemed to fix things again.

Not sure what caused this, but am suspecting that the cloudprint authentication somehow needs to be renewed periodically as required by Google? If this is the case, would be great to somehow automate this since I see that the cloudprint password is already available in /var/lib/cloudprintd/authfile (which might not be so secure anyway - I use a separate cloudprint account for that reason).

**Comment by davesteele** [comment]
The two-week authentication timeout was supposed to be addressed by 

https://github.com/davesteele/cloudprint-service/blob/master/debian/patches/0014-Refresh-XMPP-authentication-in-process_jobs.patch

- Does your version have this code?
- Are you seeing the "Refreshing authentication" log?

I expect this mechanism for authenticating will continue to degrade as Google deprecates it in favor of OAuth2.

**Comment by dbs** [comment]
I ran into the same issue, but probably because I had originally installed gcloudprint from source (around January / February 2015) before installing the package.

I suspect the older version of cloudprint.py (that was missing the patch in question) was getting picked up from my local installation rather than the package's newer version. I ran "rm -fr /usr/local/lib/python2.7/dist-packages/cloudprint", restarted the service, and we'll see in two weeks what happens :)

**Comment by jhorrell** [comment]
My issue seemed to be the same as dbs (two versions on my system - one originally installed from source, I think, which did not have the patch)

/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py (which did not have the patch)
and
/usr/share/cloudprint/cloudprint/cloudprint.py (which did have the patch)

I followed dbs and removed the dist-packages version and restarted.

Will look out for the "Refreshing authentication" message in /var/log/messages, but I guess this issue can be closed again in the meantime.

Thanks for the help and apologies for the slow response (missed dave's initial reply).
