### ISSUE TITLE
Cloudprint ignores Default Print Settings

### ISSUE THREAD

**Issue by DevilMotors** [davesteele/cloudprint-service#20]
Hey,

first of all, thanks for this nice script!

Unfortunately I have the problem that the script ignores my default printer options.

I have it set to expand onto the whole format (10x15cm or 4x6i) and portrait orientation, but it does not expand the images, nor turn into the right orientation.

When I print the same while via 'lp' on the console, the image gets printed correctly according to the default options.

Any idea how and where to change the options for the print job?

Thanks in advance,

Dennis

**Comment by davesteele** [comment]
You should raise this issue [upstream](https://github.com/armooo/cloudprint).
