### ISSUE TITLE
Debian Wheezy - error occurred during the signature verification

### ISSUE THREAD

**Issue by hubertbanas** [davesteele/cloudprint-service#21]
This is the error when apt-get udpate:

W: A error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://davesteele.github.io cloudprintppa Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 627EBB290A817A82

W: Failed to fetch http://davesteele.github.io/cloudprint-service/repo/dists/cloudprintppa/Release

**Comment by davesteele** [comment]
Sorry, I updated my key with a new signing subkey, and had not placed the new information on the hosted version. 

Repeat the instructions on the [PPA page](http://davesteele.github.io/cloudprint-service/ppa.html) to get the new key, specifically:

  # wget http://davesteele.github.io/key-366150CE.pub.txt
  # sudo apt-key add key-366150CE.pub.txt

**Comment by hubertbanas** [comment]
All good after installing new key. Thanks
