### ISSUE TITLE
failed to connect to server error

### ISSUE THREAD

**Issue by TomHart** [davesteele/cloudprint-service#23]
I've just followed your PPA instructions, but when I run `service cloudprintd login` I get an error `failed to connect to server` error. Here's the log

    root@abc:/# service cloudprintd login
    Accounts with 2 factor authentication require an application-specific password
    Traceback (most recent call last):
      File "/usr/sbin/cloudprintd", line 9, in <module>
        load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-cmd')()
      File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 480, in main
        cups_connection = cups.Connection()
    RuntimeError: failed to connect to server
    root@abc:/#

Any idea what I need to do to get this issue to go away?

**Comment by davesteele** [comment]
Under your Google 'Account Settings', do you have 'Access for less secure apps' set to 'On'?

cloudprint is currently a less secure app.

I only see this option when 2-step verification is off.

**Comment by davesteele** [comment]
This question is obsolete with OAuth2.
