### ISSUE TITLE
"cloudprintd" disappeared after upgrading it on Ubuntu 15.04

### ISSUE THREAD

**Issue by smiley** [davesteele/cloudprint-service#26]
I updated everything on the server, including `cloudprint` and the service disappeared. I can't find it under `/etc/init.d` nor `service`. Several remove-install sessions later -- with a restart for all other updates -- and it's still nowhere to be found. I used the PPA for installation and for upgrading just now.

I don't remember the exact version it was on pre-upgrade, but it was probably 0.11.6, judging by the gap in releases.

Did you change the service definition/installation flow between those two?

**Comment by davesteele** [comment]
The service has been moved to systemd.

**Comment by smiley** [comment]
Got it. I couldn't find a mention for this, can you explain this in `README.md`? And perhaps add a `/etc/init.d` shim for ease-of-use?

**Comment by davesteele** [comment]
Resolved in #36.
