### ISSUE TITLE
Systemd seems to try to start cloudprint before cups on kubuntu 15.04

### ISSUE THREAD

**Issue by kuken2** [davesteele/cloudprint-service#28]
Hey,

I installed cloudprint from your PPA on my Kubuntu 15.04 system and running cloudprint worked well, but if I tried 

# cps-auth 
...
# sudo systemctl start cloudprintd.service
# systemctl status cloudprintd.service

and rebooted my system kern.log said
Jun 29 14:26:21 kubuntu systemd[1]: Started CUPS Scheduler.
Jun 29 14:26:21 kubuntu systemd[1]: Reloading.
Jun 29 14:26:22 kubuntu systemd[1]: Started CUPS Scheduler
Jun 29 14:26:22 kubuntu systemd[1]: Started Google Cloud Print proxy service.
Jun 29 14:26:22 kubuntu systemd[1]: Starting Google Cloud Print proxy service...
Jun 29 14:26:22 kubuntu cloudprintd[3399]: Google username: Traceback (most recent call last):
Jun 29 14:26:22 kubuntu cloudprintd[3399]: File "/usr/sbin/cloudprintd", line 9, in <module>
Jun 29 14:26:22 kubuntu cloudprintd[3399]: load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-cmd')()
Jun 29 14:26:22 kubuntu cloudprintd[3399]: File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 457, in main
Jun 29 14:26:22 kubuntu cloudprintd[3399]: cpp.username = raw_input('Google username: ')
Jun 29 14:26:22 kubuntu cloudprintd[3399]: EOFError: EOF when reading a line
Jun 29 14:26:22 kubuntu systemd[1]: cloudprintd.service: main process exited, code=exited, status=1/FAILURE
Jun 29 14:26:22 kubuntu systemd[1]: Unit cloudprintd.service entered failed state.
Jun 29 14:26:22 kubuntu systemd[1]: cloudprintd.service failed.

So as a workaround I tried changing the After=cups.service line in my /lib/systemd/system/cloudprint.service to After=mediatomb.service, which on my system seems to be pretty much the last service to load, and now it works! Thought you would like to know.

J

**Comment by davesteele** [comment]
The error is a Cloud Print authentication failure. That's independent of the status of CUPS.
