### ISSUE TITLE
12.1 daemon doesn't work, 11.9 did

### ISSUE THREAD

**Issue by kuken2** [davesteele/cloudprint-service#29]
Hey,

upgraded through your PPA and now it now longer works. Running 'cloudprint' works.

● cloudprintd.service - Google Cloud Print proxy service
   Loaded: loaded (/lib/systemd/system/cloudprintd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since mon 2015-07-06 13:38:56 CEST; 3min 40s ago
  Process: 2693 ExecStart=/usr/sbin/cloudprintd -a /var/lib/cloudprintd/authfile.json (code=exited, status=1/FAILURE)
 Main PID: 2693 (code=exited, status=1/FAILURE)

jul 06 13:38:56 kubuntu systemd[1]: Starting Google Cloud Print proxy service...
jul 06 13:38:56 kubuntu cloudprintd[2693]: Google username: Traceback (most recent call last):
jul 06 13:38:56 kubuntu cloudprintd[2693]: File "/usr/sbin/cloudprintd", line 9, in <module>
jul 06 13:38:56 kubuntu cloudprintd[2693]: load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-cmd')()
jul 06 13:38:56 kubuntu cloudprintd[2693]: File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 457, in main
jul 06 13:38:56 kubuntu cloudprintd[2693]: cpp.username = raw_input('Google username: ')
jul 06 13:38:56 kubuntu cloudprintd[2693]: EOFError: EOF when reading a line
jul 06 13:38:56 kubuntu systemd[1]: cloudprintd.service: main process exited, code=exited, status=1/FAILURE
jul 06 13:38:56 kubuntu systemd[1]: Unit cloudprintd.service entered failed state.
jul 06 13:38:56 kubuntu systemd[1]: cloudprintd.service failed.

**Comment by davesteele** [comment]
What version of python-daemon do you have installed?

**Comment by davesteele** [comment]
On second thought:

The failure indicates version 0.11 - both the "/usr/sbin/cloudprintd" and "/usr/share/cloudprint/cloudprint/cloudprint.py" files. Are you sure 0.12 installed?

Note that 0.12-1 responds to a break in compatibility for python-daemon version 2.0, and won't install for an earlier version of that package.

The actual error you are seeing is an authentication error. Re-authenticate, and you should be back in business.

**Comment by davesteele** [comment]
See #30
