### ISSUE TITLE
Can't install 0.12-2

### ISSUE THREAD

**Issue by mfraser** [davesteele/cloudprint-service#30]
Now that Cloudprint has been upgraded to 0.12-2, I am unable to install it as it depends upon python-daemon (>= 2.0). I have installed version 2.0.5 of python-daemon using pip, but it still won't install and 1.5.5 is the only version available in Ubuntu http://packages.ubuntu.com/search?suite=all&section=all&arch=any&searchon=names&keywords=python-daemon

**Comment by davesteele** [comment]
The first two 0.12 releases do two things, adapt to upstream's latest release, and adapt to an upgrade to the python-daemon package that breaks compatibility to the old interface. These changes are first released to Debian unstable and testing, where they fix daemon mode breakage.

You can consider ignoring the failed upgrade, and staying with 0.11-9 for the time being. In terms of features and stability, there's not much difference. The OAuth implementation is different (the old version wants to launch a web browser), but there is not much of a driver to change, unless forced by python-daemon.

Or, you can force an upgrade, recognizing that you have the new python daemon installed ('dpkg --force-depends -I <file.deb>'). I've been mentioning this option a bit lately, and mostly regretting it. If other problems crop up, this just makes life worse.

Until/unless I start adding back features you might want, like include/exclude, I'd recommend ignoring the upgrade failure.

BTW, I believe your 0.12-1 install also failed, for the same reason. Version 0.12-2 is an attempt to avoid losing the existing authentication in that case.
