### ISSUE TITLE
cps-auth Browser Authentication

### ISSUE THREAD

**Issue by kmlucy** [davesteele/cloudprint-service#37]
Hi,

I am running Debian Jessie on a headless server. When I attempt to authorize my account with cps-auth, I get a prompt to enter code from browser authentication. How do I get the browser authentication?

Thanks.

**Comment by davesteele** [comment]
OAuth2 authentication requires a graphical browser. You need to enter that code (actually URL) into a web browser somewhere, and complete the login process there.

**Comment by kmlucy** [comment]
How do I get the URL? All I get is the prompt to enter the code. Thanks for getting back to me so fast.

**Comment by davesteele** [comment]
When I run cps-auth against 0.13-1, It says e.g. "Goto http://goo.gl/printer/VimUO to clame this printer". Ignoring the spelling errors, that URL is the place to establish that the printer is tied to your account.

**Comment by kmlucy** [comment]
I am on 0.11-9. I cannot get anything newer to install.

**Comment by davesteele** [comment]
See http://davesteele.github.io/cloudprint-service/ for later downloads, though there are reasons it may not want to install in your environment (it's looking for Debian Jessie/stable). The later 0.11 versions tried to launch the browser directly from cps-auth. If you aren't running a graphical environment, that won't work. Use cloudprint-auth on a Linux computer with a browser to generate the credential file information, and use the information in 'man cloudprint-auth' to store the information on your target computer.

**Comment by kmlucy** [comment]
Alright, I got it working. Thanks.
