### ISSUE TITLE
cps-auth

### ISSUE THREAD

**Issue by sim-sedril** [davesteele/cloudprint-service#39]
I'm having trouble trying to run "cps-auth" to authenticate.

I'm using version 0.14-3, and running Debian Stretch.

root@host:~# cps-auth
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.10', 'console_scripts', 'cloudprint')()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 387, in main
    opts, args = getopt.getopt(sys.argv[1:], 'dlhp:a:')
  File "/usr/lib/python2.7/getopt.py", line 90, in getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "/usr/lib/python2.7/getopt.py", line 190, in do_shorts
    if short_has_arg(opt, shortopts):
  File "/usr/lib/python2.7/getopt.py", line 206, in short_has_arg
    raise GetoptError('option -%s not recognized' % opt, opt)
getopt.GetoptError: option -c not recognized

Linux host 4.1.0-2-kirkwood #1 Debian 4.1.6-1 (2015-08-23) armv5tel GNU/Linux

**Comment by davesteele** [comment]
That failure didn't come from cloudprint 0.14-3. Calls to 'getopt' were eliminated in 0.12, and your 'load_entry_point' call (which is running from /usr/local/bin) is referencing 0.10. I looks like you have an old local install that is interfering with the latest package.

Try uninstalling whatever you have, and reinstall 0.14-3.

**Comment by sim-sedril** [comment]
Got it! Thanks!
