### ISSUE TITLE
SSL issues raspberry pi

### ISSUE THREAD

**Issue by giladbarkai** [davesteele/cloudprint-service#43]
Been following up on different threads, but I'm still unable to work with cloudprint.
On latest raspbian distribution with most up-to-date packages.

Install:
Downloaded the 0.13-1 packages

root@raspberrypi:/home/pi/downloads/deb# dpkg -i *.deb
Selecting previously unselected package cloudprint.
(Reading database ... 87837 files and directories currently installed.)
Unpacking cloudprint (from cloudprint_0.13-1+deb8u1+ppa1_all.deb) ...
Selecting previously unselected package cloudprint-service.
Unpacking cloudprint-service (from cloudprint-service_0.13-1+deb8u1+ppa1_all.deb) ...
Setting up cloudprint (0.13-1+deb8u1+ppa1) ...
Processing triggers for man-db ...
Setting up cloudprint-service (0.13-1+deb8u1+ppa1) ...
No authentication found - run 'service cloudprintd login' as root

Execution (and failure):
root@raspberrypi:/home/pi/downloads/deb# service cloudprintd login
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/sbin/cloudprintd", line 9, in <module>
    load_entry_point('cloudprint==0.13', 'console_scripts', 'cloudprint-cmd')()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 490, in main
    auth.login(name, description, ppd)
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 110, in login
    headers={'X-CloudPrint-Proxy': 'ArmoooIsAnOEM'},
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

I tried also the other pair of packages, no go. Tries to install with pip install cloudprint - still no go.
*Frustrated*
Please help..

**Comment by davesteele** [comment]
See https://github.com/armooo/cloudprint/issues/118
