### ISSUE TITLE
The cloudprint version in the Debian Jessie/stable repository is broken

### ISSUE THREAD

**Issue by davesteele** [davesteele/cloudprint-service#45]
cloudprint version 0.11-5, currently in the Jessie repository, does not support OAuth2. Google now requires OAuth2, meaning that the package is broken.

See http://davesteele.github.io/cloudprint-service/ for versions that will work across distributions.

The upgrade to the Jessie release is being worked as Debian bug #[800163](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800163)

**Comment by rrothermund** [comment]
Will [this](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html) announcement have any effect on cloudprint-service?

**Comment by davesteele** [comment]
I'd say 'no'. It doesn't use an embedded web view. @armooo may have better insight, though.

**Comment by armooo** [comment]
I don't think this change will be a problem. We currently use a custom oauth2 flow for that is designed for printers without an input device. So you get a short URL and complete the login on a computer. It is described as Cloud-Ready Printer here https://developers.google.com/cloud-print/docs/devguide#anonymousregistration .

**Comment by davesteele** [comment]
Due to an issue with the backport process, gnome-gmail has been removed from Debian Jessie. It remains in stretch. Jessie users can use the [PPA](http://davesteele.github.io/cloudprint-service/ppa.html)
