### ISSUE TITLE
Why does cps-auth need user credentials?

### ISSUE THREAD

**Issue by Phobetor** [davesteele/cloudprint-service#46]
According to the [Developer Guide for Printers and Connectors](https://developers.google.com/cloud-print/docs/devguide) printers and connectors should use "robot accounts" to avoid issues with API rate limits. The registration is described as making "unauthenticated" calls to get the registration token and poll for the confirmation which contains credentials of that said "robot account".

Is cloudprint using this mechanism? If so, why is it asking for user credentials? If not, is there any way to make it use these special accounts?

I am asking because I have a whole bunch of printers connected to cloud print and have serious rate limit issues.

**Comment by davesteele** [comment]
If I understand the reference correctly, the robot account is a user issue. It is up to you to create and use a separate account for the printer(s). 

If I recall correctly, there was a time that XMPP still needed the user name, even though OAuth2 was in use. That issue should not be a part of your problem.

**Comment by Phobetor** [comment]
@davesteele sorry for the hazzle. cps-auth works as expected. I accidentally used an outdated version from some third-party ppa. After changing to the standard xenial package, no credentials are required.

Thank you very much for your packages! They save a lot of time and headaches.
