### ISSUE TITLE
cps-auth missing

### ISSUE THREAD

**Issue by sepastian** [davesteele/cloudprint-service#49]
Hello,

I'm following [your instructions](https://davesteele.github.io/raspberrypi/2016/04/23/raspberry-pi-cloudprint/) on how to setup cloudprint on a Raspberry Pi running Raspbian Jessie.

The `cps-auth` command seems missing in the official Debian packages.

The notes say

> If you are running a newer version of Raspbian than Jessie, cloudprint-service is in the official repository. You don’t need to modify the apt environment.

So I did not add the apt repository manually, I'm using the officially Debian repository instead (I'm running Jessie).

Where is `cps-auth`?

**Comment by davesteele** [comment]
If you are running Jessie, you are not running a newer version of Raspbian than Jessie. You need an upgrade of the cloudprint packages, either per the instructions or from the [home page](http://davesteele.github.io/cloudprint-service/).

BTW, if you are using Raspbian Lite, and run into #48, could you try installing systemd and then rerunning?

**Comment by sepastian** [comment]
You are right, I should have read more carefully.

Added the repositories manually, now I have `cps-auth`, thanks!

I didn't run into #48, though.
