### ISSUE TITLE
Dockerizing?

### ISSUE THREAD

**Issue by a10kiloham** [davesteele/cloudprint-service#51]
I'd like to make a version of this to run as a container but I can't see where the files are written to create a volume and thus make things portable (as this config would be overwritten upon each new build after a new pull)
Cheers

**Comment by davesteele** [comment]
This particular repository is about the debian packaging, which stores authorization information in [/var/lib/cloudprintd](https://github.com/davesteele/cloudprint-service/blob/master/debian/cloudprint-service.cloudprintd.service#L7). Other data is handled by Google/CUPS.
