### ISSUE TITLE
authentication keeps failing

### ISSUE THREAD

**Issue by wdehoog** [davesteele/cloudprint-service#54]
As described in other issues (for example in 24) I ran 'sudo cps-auth' on a machine with a gui. Then I copy the file '/var/lib/cloudprintd/authfile.json' to the other machine where cups and cloudprinterd are running.

Starting cloudprinterd fails. When started with 'systemctl start cloudprintd' or with 'cloudprintd -d':
  File "/usr/share/cloudprint/cloudprint/rest.py", line 105, in rest_call
    raise REST.RESTException('REST Error', resp.status, data)
cloudprint.rest.RESTException: REST Error:404
Message: https://developers.google.com/accounts/docs/AuthForInstalledApps

I try to get it running on a BananaPi running armbian jessie.

**Comment by davesteele** [comment]
The reference to rest.py tells me you are running an old version of cloudprintd. The 404 error tells me it predates Google's mandatory conversion to OAuth2 authentication.

Take a look at the [home page](http://davesteele.github.io/cloudprint-service/). There are some pointers of better versions to download, depending on your system requirements. Beyond that, I'm not going to be much help - I don't run anything older than Stretch.

BTW, the json file copy should not be necessary, as long as you have some sort of access to the cloudprint logging.

**Comment by wdehoog** [comment]
Thanks for your response. Indeed cloudprinterd was old. The new version starts with 'cloudprintd -d'. 'systemctl start ..' fails but that is another subject.
