### ISSUE TITLE
No Location avaliable

### ISSUE THREAD

**Issue by Error-101** [davesteele/cloudprint-service#55]
The service is working great and is very smooth. Only issue (really a non-issue) is that the location parameter doesn't set. Is there any way to fix this or could you point me in the direction of the file that sets it so I can have a look myself?

**Comment by davesteele** [comment]
That is an [upstream](https://github.com/armooo/cloudprint) issue. I suspect the solution will be similar to [this](https://github.com/armooo/cloudprint/commit/108b9f02669e141a499e339ed6bf098c5553dabc).
