### ISSUE TITLE
Missing dependency on "requests"

### ISSUE THREAD

**Issue by davesteele** [davesteele/cloudprint-service#56]
There is a missing Depends on ${python3:Depends}. In Buster, this is leading to a missing "requests" package.

A valid workaround should be to install the python3-requests pacakge.

Reported as armooo/cloudprint#142

**Comment by MichaIng** [comment]
@davesteele 
Sorry for the obsolete bug report then: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954310
However, as you are the Debian package maintainer as well, would it be possible to update the Debian Buster downstream package accordingly? Indeed no big deal to install `python3-requests` manually but inexperienced might not find this solution, which is not nice to have in current stable Debian release, is it?

**Comment by davesteele** [comment]
All I can offer is [this](https://github.com/davesteele/comitup/issues/102#issuecomment-586780754), and note that cloudprint will die at the end of the year.

**Comment by MichaIng** [comment]
@davesteele 
> Buster is Debian's current stable release. It's non-trivial to get changes into that version in a way that is generally visible to users.

That makes it clear, although a problem that such obvious bugs with one-line/word fixes cannot be merged easily into Debian stable. I understand the general policy of Debian, but in some cases faster/easier package updates would be great...

However off topic, all I found is in master/upstream now, or was already, thanks for this 👍.
