### ISSUE TITLE
"Update Required" Message

### ISSUE THREAD

**Issue by wozzo** [davesteele/cloudprint-service#6]
I've got a RPi running raspbian, to which I have installed cloudprint following the instructions here - http://davesteele.github.io/cloudprint-service/ppa.html
The printer had been tested with cups, and chromium allowed use of it as a Google cloud printer too, but using cloudprint the printer appears as online, but jobs remain in the queue.

On the google cloud print management page for the printer the message "Update Required" appears next to the job, which directs me to this page - https://support.google.com/cloudprint/?hl=en#3210000

Any ideas? I'm very new to Linux.

**Comment by davesteele** [comment]
Question answered at https://github.com/armooo/cloudprint/issues/111#issuecomment-133545224
